on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Test

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-18.04 ]
        php: [ '7.2', '7.4' ]
        #operating-system: [ ubuntu-18.04, windows-2019 ]
        #php: [ '7.2', '7.4', '8.0' ]
    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: nanasess/setup-php@v3
        with:
          php-version: ${{ matrix.php }}
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Set example Git user
        run: git config --global user.email "testbot@example.com" && git config --global user.name "Test Bot"
      - run: ./scripts/test.sh
