on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Test

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
          - operating-system: ubuntu-latest
            php: 7.3
            phpunit: 8
          - operating-system: ubuntu-latest
            php: 7.4
            phpunit: 8
          - operating-system: ubuntu-latest
            php: 8.1
            phpunit: 9
          - operating-system: windows-2019
            php: '7.3'
            phpunit: 8
    name: PHP ${{ matrix.php }}
    steps:
      - name: Set example Git user
        run: git config --global user.email "testbot@example.com" && git config --global user.name "Test Bot"
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml.dist
          version: ${{ matrix.phpunit }}
          php_version:  ${{ matrix.php }}
